# Build Stage
FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build ws service (cmd/ws/main.go)
RUN go build -o chat-service ./cmd/ws

# Runtime Stage
FROM alpine:3.19
WORKDIR /app

COPY --from=builder /app/chat-service .

EXPOSE 9000

CMD ["./chat-service"]
